### ISSUE TITLE
Serial monitor not displaying content

### ISSUE THREAD

**Issue by Sanyam02** [BlocklyDuino/BlocklyDuino-v2#10]
After downloading your installation, the serial monitor is not displaying the content from the serial port.
![SS](https://user-images.githubusercontent.com/68013436/92319617-facfa080-f037-11ea-9f60-681557bf34b4.jpg)

**Comment by SebCanet** [comment]
Strange thing...I'll try it again. Thanks.

**Comment by sam-tj** [comment]
did this work?

**Comment by SebCanet** [comment]
Fixed! Thanks for tests.
