### ISSUE TITLE
UI choices - accessibility

### ISSUE THREAD

**Issue by SebCanet** [BlocklyDuino/BlocklyDuino-v2#14]
As seen in TurtleStudio ([https://sam-tj.github.io/Turtle-Studio-v1/](https://sam-tj.github.io/Turtle-Studio-v1/)), UI interface could be dispatched in different places. The aim is make it simpliest as possible, for kids and newbies.
I don't want to remove any option (or it's another discussion, to decide what is useful or not for accesibility, and kids with colorblindings problem, etc) but decide what we can put where.

I'm working on new UI where all option are in a single panel but with accordion menus:
![Image 1](https://user-images.githubusercontent.com/6362199/92407073-e5429f80-f139-11ea-93ad-4cee75bd0755.png)

Any suggestion?

**Comment by sam-tj** [comment]
Looks good. 
Would suggest that board selection should be somewhere on front UI because without selecting a board the blocks cannot be used.

**Comment by Yann-le-Chevoir** [comment]
Hello, thanks Séb for pointing me to BlocklyDuino-v2. Will definitely have a look.
+1 to force the user to select a board and/or set one as default.
As a newby, I did not understand why I did not have access to the Arduino blocks right away. There is the one for the embedded led which seems available but that we can not select, looks more like a bug, I had the feeling that the Arduino blocks were not developped yet.
For "my" forked version, I think I will hardcode the board used by my students in BlocklyDuino-v2/blocklyduino/js/boards.js
`if (!boardId) {
  boardId = "arduino_nano";
}`
Maybe you can set arduino_uno as the official default one?

**Comment by SebCanet** [comment]
What I can do is to create a default toolbox, with just the few categories from algorithm (the same as Scratch: logic, loops, ..., functions) and Arduino only appears if you select a board.
The board choice is in front UI, it's through the right icon. you have to select a board before using blocks because pin numbers are different, that's why I think the idea a 'default' board is not a good idea for newbies.
