### ISSUE TITLE
Serial-blocks not working

### ISSUE THREAD

**Issue by andre-dietrich** [BlocklyDuino/BlocklyDuino-v2#27]
Hi, I adapted your great Editor, so that it can be used in edrys as a module for teaching programming:

https://github.com/Cross-Lab-Project/edrys_module-blockly-duino-v2

I currently have the Problem, that Serial-communication for Arduino does not work, there are no blocks presented, as depicted in the screenshot of your demo:

![image](https://github.com/BlocklyDuino/BlocklyDuino-v2/assets/3089101/3ca3d413-da2a-449a-801e-67f9f838d8f7)

Is it possible to add some serial blocks to your project?

Thanks in advance

**Comment by SebCanet** [comment]
Wow! What a great project! Thanks for trying to incorporate my work.
However, there are still some gaps in it...it's worth trying to integrate Studio4Education ([https://github.com/A-S-T-U-C-E/STudio4Education](https://github.com/A-S-T-U-C-E/STudio4Education)).
In any case, in both cases, as the blocks for the boards are configured according to the board, you first have to choose the board: click on the icon in the shape of a microchip, next to the hyperlink icon.
Then the Arduino categories will work.

**Comment by andre-dietrich** [comment]
Very nice, thank you, now I can see the control elements... I will also have a look at studio4education ... The edrys idea is to have as many replaceable modules/editors as possible ... Thanks a lot ...

**Comment by SebCanet** [comment]
Keep in touch and tell me when you have finished! Very hurry to see it working, and maybe communicating with Arduino board.

**Comment by andre-dietrich** [comment]
I already added the board option to the settings for:

https://github.com/Cross-Lab-Project/edrys_module-blockly-duino-v2

works like charm ... For the other editor I will have to take a deeper look into the code ;-)

Thanks anyways ...
